version: 2
updates:
- package-ecosystem: pip
  directory: "/src"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - edelbluth
  assignees:
  - edelbluth
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.3
    - 2.7.4
    - 2.8.1
  - dependency-name: coverage
    versions:
    - "5.4"
