language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -U pip setuptools
  - pip install -r src/test-requirements.txt
  - pip install coveralls

script:
  - (cd src && make ci)

after_success:
  - (cd src && coveralls --rcfile=coverage.rc)

notifications:
  email:
    on_success: change
    on_failure: always
