language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install -U pip setuptools
  - pip install -r test-requirements.txt
  - pip install coveralls

script:
  - (cd src && make ci)

after_success:
  - (cd src && coveralls --rcfile=coverage.rc)

notifications:
  email:
    on_success: change
    on_failure: always
